language: ruby

rvm:
 - 2.6

services: postgresql

addons:
  postgresql: "9.4"

before_install:
  - cp config/database.yml.sample config/database.yml
  - export RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - gem install bundler:2.0.1
  - bundle install
  - nvm install 10.15
  - node -v
  - npm i -g yarn
  - yarn install

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rails webpacker:compile
  - bundle exec rake

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: historical
  strategi: api
