language: ruby

rvm:
 - 2.4

services: postgresql

before_install:
  - cp config/database.yml.sample config/database.yml
  - export RAILS_ENV=test

cache:
  directories:
    - vendor/bundle

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: historical
  strategi: api
